trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'

- script: |
    npm test
  displayName: 'npm test'

- task: ArchiveFiles@2
  displayName: 'Archive files'
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false

- task: PublishBuildArtifacts@1
  displayName: 'Publish artifacts: drop'
  
- task: SnykSecurityScan@1
  inputs:
    serviceConnectionEndpoint: 'snykConnect'
    testType: 'app'
    monitorWhen: 'always'
    failOnIssues: true
    projectName: 'node-express-azure'
    organization: 'jacobpalomo21'
    
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.8'
  displayName: 'Install Python 3.8'
- script: pip install bridgecrew
  displayName: 'Install the Bridgecrew CLI'
- script: bridgecrew -d jakethekid21/node-express-azure --bc-api-key dcc4fee1-f2e0-4c5e-b870-882dda7e9cf6 --repo-id jakethekid21/node-express-azure --branch master
  displayName: 'Scan with Bridgecrew'
